on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Check Node v
        run: node -v
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: zip create
        run: zip -qq -r ./build-fe.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://coc-stats-bucket/build-fe.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name coc-stats-code-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name coc-stats-code-deploy-group
          --s3-location bucket=coc-stats-bucket,key=${{ secrets.BUILD_DIRECTORY }},bundleType=zip
